### ISSUE TITLE
is_selinux_enabled() always returns false

### ISSUE THREAD

**Issue by traveaston** [pycontribs/selinux#9]
Function regression was introduced in de013cb, link to the patch here: https://github.com/pycontribs/selinux/commit/de013cb6ecfa223bdd981ba5e156326da94e7152#diff-1b99a3b1021efb37ca6c3140b08a0c48

**Comment by ssbarnea** [comment]
@traveaston I released 0.1.5rc1 which is uspposed to fix that, please test it an comment with results, so I know if it fixes your issue or not.

**Comment by traveaston** [comment]
Still not working as expected, is_selinux_enabled() still returns false due to this line: https://github.com/pycontribs/selinux/blob/a1d0dc3eeb6e577e16ac3d643a61265c464b601c/selinux/__init__.py#L39

Bash output:

```
root at cobalt in /home/trav
# cat /etc/*-release
CentOS Linux release 7.6.1810 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.6.1810 (Core)
CentOS Linux release 7.6.1810 (Core)

root at cobalt in /home/trav
# python3 -m pip show selinux
Name: selinux
Version: 0.1.5rc1
Summary: shim selinux module
Home-page: https://github.com/pycontribs/selinux
Author: Sorin Sbarnea
Author-email: sorin.sbarnea@gmail.com
License: MIT license
Location: /usr/local/lib/python3.6/site-packages
Requires:
Required-by:

root at cobalt in /home/trav
# python3
Python 3.6.8 (default, Apr 25 2019, 21:02:35)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import selinux
>>> selinux.is_selinux_enabled()
0
>>>

root at cobalt in /home/trav
# getenforce
Enforcing
```
